### ISSUE TITLE
Opening the same file through a different link will close the file that opened it

### ISSUE THREAD

**Issue by jiajiala** [1C0D/Obsidian-Close-Similar-Tabs#34] opened 2024-03-04 00:21 UTC
Let's say I open an A1 file through A file
Then I open the A1 file through the B file
B The file will be closed

**Comment by 1C0D** [comment] 2024-03-05 15:47
That's perfectly normal if you press ctrl it won't happen.
if you press the link A1 in the page A, the page becomes A1
if you press A1 in the page B, the page becomes A1 so it's a duplicated page, it's closed.
if you press ctrl instead B will remain opened and the duplicate of A1 closed

**Closed by 1C0D** 2024-03-05 15:47 UTC
